///////////////////////////////////////////////////////////
//  GetBookmarkRuleProvider.cs
//  Implementation of the Class GetBookmarkRuleProvider
//  Generated by Enterprise Architect
//  Created on:      30-1月-2019 8:32:00
//  Original author: 张楠
///////////////////////////////////////////////////////////
///
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using org.activiti.bpmn.constants;
using org.activiti.bpmn.model;
using org.activiti.engine.@delegate;
using org.activiti.engine.exceptions;
using org.activiti.engine.impl.context;
using org.activiti.engine.impl.persistence.entity;
using org.activiti.engine.impl.util;
using Sys;
using Sys.Workflow;
using Sys.Workflow.Engine.Bpmn.Rules;
using System;
using System.Collections.Generic;
using System.Linq;

namespace org.activiti.engine.impl.bpmn.listener
{
    /// <summary>
    /// 运行时分配节点运行人员,监听节点的Excution创建事件,在流程进入节点时根据当前数据变量获取
    /// 当前节点任务处理人
    /// </summary>
    public class RuntimeAssigneeExecutionListener : IExecutionListener
    {
        private readonly ILogger<RuntimeAssigneeExecutionListener> logger =
            ProcessEngineServiceProvider.LoggerService<RuntimeAssigneeExecutionListener>();

        /// <summary>
        /// 侦听接收通知处理
        /// </summary>
        /// <param name="execution"></param>
        public void notify(IExecutionEntity execution)
        {
            UserTask task = execution.CurrentFlowElement as UserTask;

            if (task.ExtensionElements.TryGetValue("property", out IList<ExtensionElement> exts))
            {
                if (bool.TryParse(exts.GetAttributeValue(BpmnXMLConstants.ACTIITI_RUNTIME_ASSIGNEE), out bool result) == false || result == false)
                {
                    return;
                }

                var variable = execution.getVariableInstance(BpmnXMLConstants.RUNTIME_ASSIGNEE_USER_VARIABLE_NAME);

                RuntimeAssigneeUser user = JToken.FromObject(variable.Value).ToObject<RuntimeAssigneeUser>();

                if (user.Users?.Count() == 0)
                {
                    throw new NotFoundAssigneeException();
                }

                var varName = exts.GetAttributeValue(BpmnXMLConstants.ACTIITI_RUNTIME_ASSIGNEE_VARIABLE);

                if (string.IsNullOrWhiteSpace(varName))
                {
                    varName = user.Field;
                }

                execution.SetLoopVariable(varName, user.Users.Distinct().ToArray());
            }
        }
    }
}
