///////////////////////////////////////////////////////////
//  GetBookmarkRuleProvider.cs
//  Implementation of the Class GetBookmarkRuleProvider
//  Generated by Enterprise Architect
//  Created on:      30-1月-2019 8:32:00
//  Original author: 张楠
///////////////////////////////////////////////////////////

using org.activiti.engine;
using System;
using System.Runtime.Serialization;

namespace org.activiti.engine.exceptions
{
    /// <summary>
    /// 已存在的获取会签用户规则类型
    /// </summary>
    [Serializable]
    public class ExistsRuleTypeException : ActivitiException
    {
        public ExistsRuleTypeException(string ruleName, Type ruleType)
            : base($"exists {ruleType.FullName} with {ruleName}")
        {
        }
    }
}