///////////////////////////////////////////////////////////
//  GetBookmarkRuleProvider.cs
//  Implementation of the Class GetBookmarkRuleProvider
//  Generated by Enterprise Architect
//  Created on:      30-1月-2019 8:32:00
//  Original author: 张楠
///////////////////////////////////////////////////////////

using Sys.Workflow.engine;
using System;
using System.Runtime.Serialization;

namespace Sys.Workflow.engine.exceptions
{
    /// <summary>
    /// 不存在的会签角色规则
    /// </summary>
    [Serializable]
    public class NotExistsRuleTypeException : ActivitiException
    {
        public NotExistsRuleTypeException(string ruleName) : base($"Not exists {ruleName}")
        {
        }
    }
}