///////////////////////////////////////////////////////////
//  IUserServiceProxy.cs
//  Implementation of the Interface IUserServiceProxy
//  Generated by Enterprise Architect
//  Created on:      30-1月-2019 8:32:00
//  Original author: 张楠
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Threading.Tasks;

namespace Sys.Workflow.Engine.Bpmn.Rules
{
    /// <summary>
    /// 用户服务WebApi代理类
    /// </summary>
    public interface IUserServiceProxy
    {
        /// <summary>
        /// 获取用户信息
        /// </summary>
        /// <param name="apiUrl">服务地址</param>
        /// <param name="parameter">请求参数</param>
        [Obsolete("使用GetUsers(string apiUrl, RequestUserParameter parameter)")]
        Task<IList<IUserInfo>> GetUsers(string apiUrl, object parameter);
        /// <summary>
        /// 获取用户信息
        /// </summary>
        /// <param name="apiUrl">服务地址</param>
        /// <param name="parameter">请求参数</param>
        Task<IList<IUserInfo>> GetUsers(string apiUrl, RequestUserParameter parameter);

        /// <summary>
        /// 获取用户信息
        /// </summary>
        /// <param name="apiUrl">服务地址</param>
        /// <param name="parameter">请求参数</param>
        [Obsolete("使用GetUsers(RequestUserParameter parameter)")]
        Task<IList<IUserInfo>> GetUsers(object parameter);

        /// <summary>
        /// 获取用户信息
        /// </summary>
        /// <param name="apiUrl">服务地址</param>
        /// <param name="parameter">请求参数</param>
        Task<IList<IUserInfo>> GetUsers(RequestUserParameter parameter);

        /// <summary>
        /// 获取用户信息
        /// </summary>
        /// <param name="apiUrl">服务地址</param>
        /// <param name="parameter">请求参数</param>
        Task<IUserInfo> GetUser(string userId);

        /// <summary>
        /// 获取用户信息
        /// </summary>
        /// <param name="apiUrl">服务地址</param>
        /// <param name="userId">userId</param>
        Task<IUserInfo> GetUser(string apiUrl, string userId);
    }
}