///////////////////////////////////////////////////////////
//  GetBookmarkRuleProvider.cs
//  Implementation of the Class GetBookmarkRuleProvider
//  Generated by Enterprise Architect
//  Created on:      30-1月-2019 8:32:00
//  Original author: 张楠
///////////////////////////////////////////////////////////

using System;
using System.Runtime.Serialization;

namespace Sys.Workflow.Engine.Bpmn.Rules
{
    [Serializable]
    public class ExistsRuleTypeException : Exception
    {
        public ExistsRuleTypeException(string ruleName, Type ruleType)
            : base($"exists {ruleType.FullName} with {ruleName}")
        {
        }
    }
}