///////////////////////////////////////////////////////////
//  GetDeptLeaderBookmarkRuleCmd.cs
//  Implementation of the Class GetDeptLeaderBookmarkRuleCmd
//  Generated by Enterprise Architect
//  Created on:      30-1月-2019 8:32:00
//  Original author: 张楠
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using org.activiti.engine.impl.interceptor;

namespace Sys.Workflow.Engine.Bpmn.Rules
{
    /// <summary>
    /// 根据人员id查找所在部门领导
    /// </summary>
    [GetBookmarkDescriptor("GetDeptLeader")]
    public class GetDeptLeaderBookmarkRuleCmd : IGetBookmarkRule
    {

        public GetDeptLeaderBookmarkRuleCmd()
        {

        }

        public QueryBookmark Condition { get; set; }

        /// 
        /// <param name="userId"></param>
        private IList<IUserInfo> 获取用户所在部门领导(string userId)
        {

            return null;
        }

        public IList<IUserInfo> execute(ICommandContext commandContext)
        {
            throw new NotImplementedException();
        }
    }
}