///////////////////////////////////////////////////////////
//  GetDeptBookmarkRuleCmd.cs
//  Implementation of the Class GetDeptBookmarkRuleCmd
//  Generated by Enterprise Architect
//  Created on:      30-1月-2019 8:32:00
//  Original author: 张楠
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Sys.Workflow.Engine.Impl.Interceptor;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Options;
using System.Linq;

namespace Sys.Workflow.Engine.Bpmn.Rules
{
    /// <summary>
    /// 根据部门id获取部门下的所有用户信息
    /// </summary>
    [GetBookmarkDescriptor("GetDept")]
    public class GetDeptBookmarkRuleCmd : BaseGetBookmarkRule
    {
        private readonly ExternalConnectorProvider externalConnector;

        /// <inheritdoc />
        public GetDeptBookmarkRuleCmd()
        {
            externalConnector = ProcessEngineServiceProvider.Resolve<ExternalConnectorProvider>();
        }

        /// <inheritdoc />
        public override IList<IUserInfo> Execute(ICommandContext commandContext)
        {
            IUserServiceProxy proxy = ProcessEngineServiceProvider.Resolve<IUserServiceProxy>();

            return proxy.GetUsers(externalConnector.GetUserByDept, new
            {
                idList = Condition.QueryCondition.Select(x => x.Id).ToArray()
            }).ConfigureAwait(false).GetAwaiter().GetResult();
        }
    }
}