///////////////////////////////////////////////////////////
//  GetUserBookmarkRuleCmd.cs
//  Implementation of the Class GetUserBookmarkRuleCmd
//  Generated by Enterprise Architect
//  Created on:      30-1月-2019 8:32:00
//  Original author: 张楠
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using org.activiti.engine.impl.interceptor;

namespace Sys.Workflow.Engine.Bpmn.Rules
{
    /// <summary>
    /// 根据用户id获取用户信息
    /// </summary>
    [GetBookmarkDescriptor("GetUser")]
    public class GetUserBookmarkRuleCmd : IGetBookmarkRule
    {
        public GetUserBookmarkRuleCmd()
        {

        }

        public QueryBookmark Condition { get; set; }

        /// 
        /// <param name="userIds"></param>
        private IList<IUserInfo> 获取用户信息(string[] userIds)
        {

            return null;
        }

        public IList<IUserInfo> execute(ICommandContext commandContext)
        {
            throw new NotImplementedException();
        }
    }
}