///////////////////////////////////////////////////////////
//  IGetBookmarkRuleProvider.cs
//  Implementation of the Interface IGetBookmarkRuleProvider
//  Generated by Enterprise Architect
//  Created on:      30-1月-2019 8:32:00
//  Original author: 张楠
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace Sys.Workflow.Engine.Bpmn.Rules {

    /// <summary>
    /// 流程会签角色提供工厂类
    /// </summary>
	public interface IGetBookmarkRuleProvider
    {
        /// <summary>
        /// 创建会签角色
        /// </summary>
        /// <param name="ruleName">会签角色规则类名称</param>
        IGetBookmarkRule CreateBookmarkRule(string ruleName);

        /// <summary>
        /// 注册会签角色获取提供类
        /// </summary>
        /// <param name="ruleName"></param>
        /// <param name="ruleType"></param>
        void Register(string ruleName, Type ruleType);
	}
}