///////////////////////////////////////////////////////////
//  IGetBookmarkRule.cs
//  Implementation of the Interface IGetBookmarkRule
//  Generated by Enterprise Architect
//  Created on:      30-1月-2019 8:32:00
//  Original author: 张楠
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using Sys.Workflow.Engine.Bpmn.Rules;
using Sys.Workflow.engine.impl.interceptor;
using Sys.Workflow.engine.impl.persistence.entity;

namespace Sys.Workflow.Engine.Bpmn.Rules
{
    /// <summary>
    /// 会签角色获取接口
    /// </summary>
    public interface IGetBookmarkRule : ICommand<IList<IUserInfo>>
    {
        /// <summary>
        /// 运行实例id
        /// </summary>
        IExecutionEntity Execution { get; set; }

        /// <summary>
        /// 会签角色查询条件
        /// </summary>
        QueryBookmark Condition { get; set; }
    }
}