///////////////////////////////////////////////////////////
//  IUserServiceProxy.cs
//  Implementation of the Interface IUserServiceProxy
//  Generated by Enterprise Architect
//  Created on:      30-1月-2019 8:32:00
//  Original author: 张楠
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Sys.Workflow.Engine.Bpmn.Rules
{
    /// <summary>
    /// 用户服务WebApi代理类
    /// </summary>
    public interface IUserServiceProxy
    {
        /// <summary>
        /// 获取用户信息
        /// </summary>
        /// <param name="apiUrl">服务地址</param>
        /// <param name="parameter">请求参数</param>
        IList<IUserInfo> GetUsers(string apiUrl, object parameter);
        /// <summary>
        /// 获取用户信息
        /// </summary>
        /// <param name="apiUrl">服务地址</param>
        /// <param name="parameter">请求参数</param>
        IList<IUserInfo> GetUsers(object parameter);
    }
}