///////////////////////////////////////////////////////////
//  QueryBookmark.cs
//  Implementation of the Class QueryBookmark
//  Generated by Enterprise Architect
//  Created on:      30-1月-2019 8:32:00
//  Original author: 张楠
///////////////////////////////////////////////////////////


namespace Sys.Workflow.Engine.Bpmn.Rules
{
    /// <summary>
    /// 会签人员查询条件
    /// </summary>

    public class QueryCondition
    {
        /// <summary>
        /// 主标识id
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// 名称
        /// </summary>
        public string Name { get; set; }
    }
}