///////////////////////////////////////////////////////////
//  QueryBookmark.cs
//  Implementation of the Class QueryBookmark
//  Generated by Enterprise Architect
//  Created on:      30-1月-2019 8:32:00
//  Original author: 张楠
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace Sys.Workflow.Engine.Bpmn.Rules
{
    public class QueryBookmark
    {

        public QueryBookmark()
        {

        }
    }
}