//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sys.Workflow.Validation {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProcessValidatorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProcessValidatorResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sys.Bpm.Rest.Client.ProcessValidatorResource", typeof(ProcessValidatorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 不允许讲所有流程定义都被设置为不可执行的(流程的属性“isExecutable”). 的本地化字符串。
        /// </summary>
        internal static string ALL_PROCESS_DEFINITIONS_NOT_EXECUTABLE {
            get {
                return ResourceManager.GetString("ALL_PROCESS_DEFINITIONS_NOT_EXECUTABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关联元素缺少属性“sourceRef” 的本地化字符串。
        /// </summary>
        internal static string ASSOCIATION_INVALID_SOURCE_REFERENCE {
            get {
                return ResourceManager.GetString("ASSOCIATION_INVALID_SOURCE_REFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关联元素缺少属性“targetRef” 的本地化字符串。
        /// </summary>
        internal static string ASSOCIATION_INVALID_TARGET_REFERENCE {
            get {
                return ResourceManager.GetString("ASSOCIATION_INVALID_TARGET_REFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅在事务子流程上支持带有取消定义的边界事件 的本地化字符串。
        /// </summary>
        internal static string BOUNDARY_EVENT_CANCEL_ONLY_ON_TRANSACTION {
            get {
                return ResourceManager.GetString("BOUNDARY_EVENT_CANCEL_ONLY_ON_TRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的事件定义类型 的本地化字符串。
        /// </summary>
        internal static string BOUNDARY_EVENT_INVALID_EVENT_DEFINITION {
            get {
                return ResourceManager.GetString("BOUNDARY_EVENT_INVALID_EVENT_DEFINITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BPMN Model名称空间长度不能大于{0} 的本地化字符串。
        /// </summary>
        internal static string BPMN_MODEL_TARGET_NAMESPACE_TOO_LONG {
            get {
                return ResourceManager.GetString("BPMN_MODEL_TARGET_NAMESPACE_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 “activityRef”的属性值无效:找不到指定的活动 的本地化字符串。
        /// </summary>
        internal static string COMPENSATE_EVENT_INVALID_ACTIVITY_REF {
            get {
                return ResourceManager.GetString("COMPENSATE_EVENT_INVALID_ACTIVITY_REF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须填写数据对象名称 的本地化字符串。
        /// </summary>
        internal static string DATA_OBJECT_MISSING_NAME {
            get {
                return ResourceManager.GetString("DATA_OBJECT_MISSING_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引用无效:{0},不是一个流节点 的本地化字符串。
        /// </summary>
        internal static string DI_DOES_NOT_REFERENCE_FLOWNODE {
            get {
                return ResourceManager.GetString("DI_DOES_NOT_REFERENCE_FLOWNODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引用了一个无效的顺序流{0} 的本地化字符串。
        /// </summary>
        internal static string DI_DOES_NOT_REFERENCE_SEQ_FLOW {
            get {
                return ResourceManager.GetString("DI_DOES_NOT_REFERENCE_SEQ_FLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引用无效:找不到{0} 的本地化字符串。
        /// </summary>
        internal static string DI_INVALID_REFERENCE {
            get {
                return ResourceManager.GetString("DI_INVALID_REFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dmn活动中没有定义决策表引用键 的本地化字符串。
        /// </summary>
        internal static string DMN_TASK_NO_KEY {
            get {
                return ResourceManager.GetString("DMN_TASK_NO_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅在事务子流程内部支持取消定义结束事件 的本地化字符串。
        /// </summary>
        internal static string END_EVENT_CANCEL_ONLY_INSIDE_TRANSACTION {
            get {
                return ResourceManager.GetString("END_EVENT_CANCEL_ONLY_INSIDE_TRANSACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 errorCode不能为空 的本地化字符串。
        /// </summary>
        internal static string ERROR_MISSING_ERROR_CODE {
            get {
                return ResourceManager.GetString("ERROR_MISSING_ERROR_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基于事件的网关只能连接到中间匹配事件 的本地化字符串。
        /// </summary>
        internal static string EVENT_GATEWAY_ONLY_CONNECTED_TO_INTERMEDIATE_EVENTS {
            get {
                return ResourceManager.GetString("EVENT_GATEWAY_ONLY_CONNECTED_TO_INTERMEDIATE_EVENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须填写侦听器类型 的本地化字符串。
        /// </summary>
        internal static string EVENT_LISTENER_IMPLEMENTATION_MISSING {
            get {
                return ResourceManager.GetString("EVENT_LISTENER_IMPLEMENTATION_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的事件侦听器类型 的本地化字符串。
        /// </summary>
        internal static string EVENT_LISTENER_INVALID_THROW_EVENT_TYPE {
            get {
                return ResourceManager.GetString("EVENT_LISTENER_INVALID_THROW_EVENT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事件子流程的开始事件必须是“错误”、“消息”或“信号”类型 的本地化字符串。
        /// </summary>
        internal static string EVENT_SUBPROCESS_INVALID_START_EVENT_DEFINITION {
            get {
                return ResourceManager.GetString("EVENT_SUBPROCESS_INVALID_START_EVENT_DEFINITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计时器需要配置(日期、周期或持续时间) 的本地化字符串。
        /// </summary>
        internal static string EVENT_TIMER_MISSING_CONFIGURATION {
            get {
                return ResourceManager.GetString("EVENT_TIMER_MISSING_CONFIGURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只有一个输出序列流的条件转移不允许设置条件 的本地化字符串。
        /// </summary>
        internal static string EXCLUSIVE_GATEWAY_CONDITION_NOT_ALLOWED_ON_SINGLE_SEQ_FLOW {
            get {
                return ResourceManager.GetString("EXCLUSIVE_GATEWAY_CONDITION_NOT_ALLOWED_ON_SINGLE_SEQ_FLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不允许默认序列流有一个条件 的本地化字符串。
        /// </summary>
        internal static string EXCLUSIVE_GATEWAY_CONDITION_ON_DEFAULT_SEQ_FLOW {
            get {
                return ResourceManager.GetString("EXCLUSIVE_GATEWAY_CONDITION_ON_DEFAULT_SEQ_FLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条件转移没有设置目标节点 的本地化字符串。
        /// </summary>
        internal static string EXCLUSIVE_GATEWAY_NO_OUTGOING_SEQ_FLOW {
            get {
                return ResourceManager.GetString("EXCLUSIVE_GATEWAY_NO_OUTGOING_SEQ_FLOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条件转移至少有一个无条件的输出序列流(不是默认的) 的本地化字符串。
        /// </summary>
        internal static string EXCLUSIVE_GATEWAY_SEQ_FLOW_WITHOUT_CONDITIONS {
            get {
                return ResourceManager.GetString("EXCLUSIVE_GATEWAY_SEQ_FLOW_WITHOUT_CONDITIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须填写时间侦听器类型 的本地化字符串。
        /// </summary>
        internal static string EXECUTION_LISTENER_IMPLEMENTATION_MISSING {
            get {
                return ResourceManager.GetString("EXECUTION_LISTENER_IMPLEMENTATION_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表达式不能被使用在事务上下文中 的本地化字符串。
        /// </summary>
        internal static string EXECUTION_LISTENER_INVALID_IMPLEMENTATION_TYPE {
            get {
                return ResourceManager.GetString("EXECUTION_LISTENER_INVALID_IMPLEMENTATION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须填写ID,并且长度不能大于255 的本地化字符串。
        /// </summary>
        internal static string ID_TOO_LONG {
            get {
                return ResourceManager.GetString("ID_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的中间捕获事件类型 的本地化字符串。
        /// </summary>
        internal static string INTERMEDIATE_CATCH_EVENT_INVALID_EVENTDEFINITION {
            get {
                return ResourceManager.GetString("INTERMEDIATE_CATCH_EVENT_INVALID_EVENTDEFINITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中间捕获事件没有事件定义 的本地化字符串。
        /// </summary>
        internal static string INTERMEDIATE_CATCH_EVENT_NO_EVENTDEFINITION {
            get {
                return ResourceManager.GetString("INTERMEDIATE_CATCH_EVENT_NO_EVENTDEFINITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有定义邮件内容:Text, html, textVar or htmlVar 的本地化字符串。
        /// </summary>
        internal static string MAIL_TASK_NO_CONTENT {
            get {
                return ResourceManager.GetString("MAIL_TASK_NO_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有定义邮件接收人 的本地化字符串。
        /// </summary>
        internal static string MAIL_TASK_NO_RECIPIENT {
            get {
                return ResourceManager.GetString("MAIL_TASK_NO_RECIPIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到id为{0}的‘messageRef’ 的本地化字符串。
        /// </summary>
        internal static string MESSAGE_EVENT_INVALID_MESSAGE_REF {
            get {
                return ResourceManager.GetString("MESSAGE_EVENT_INVALID_MESSAGE_REF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须填写‘messageRef’属性 的本地化字符串。
        /// </summary>
        internal static string MESSAGE_EVENT_MISSING_MESSAGE_REF {
            get {
                return ResourceManager.GetString("MESSAGE_EVENT_MISSING_MESSAGE_REF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持具有相同消息id的多个消息事件 的本地化字符串。
        /// </summary>
        internal static string MESSAGE_EVENT_MULTIPLE_ON_BOUNDARY_SAME_MESSAGE_ID {
            get {
                return ResourceManager.GetString("MESSAGE_EVENT_MULTIPLE_ON_BOUNDARY_SAME_MESSAGE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有找到引用项 的本地化字符串。
        /// </summary>
        internal static string MESSAGE_INVALID_ITEM_REF {
            get {
                return ResourceManager.GetString("MESSAGE_INVALID_ITEM_REF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须填写名称,并且长度不能大于255 的本地化字符串。
        /// </summary>
        internal static string NAME_TOO_LONG {
            get {
                return ResourceManager.GetString("NAME_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作的消息无效 的本地化字符串。
        /// </summary>
        internal static string OPERATION_INVALID_IN_MESSAGE_REFERENCE {
            get {
                return ResourceManager.GetString("OPERATION_INVALID_IN_MESSAGE_REFERENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程备注长度不能大于{0} 的本地化字符串。
        /// </summary>
        internal static string PROCESS_DEFINITION_DOCUMENTATION_TOO_LONG {
            get {
                return ResourceManager.GetString("PROCESS_DEFINITION_DOCUMENTATION_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的流程ID‘{0}’定义,必须字母开头并且不能是UNICODE字符. 的本地化字符串。
        /// </summary>
        internal static string PROCESS_DEFINITION_ID_NOTSUPPORT_IDENTIFIER {
            get {
                return ResourceManager.GetString("PROCESS_DEFINITION_ID_NOTSUPPORT_IDENTIFIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须填写流程ID,并且长度不能大于{0} 的本地化字符串。
        /// </summary>
        internal static string PROCESS_DEFINITION_ID_TOO_LONG {
            get {
                return ResourceManager.GetString("PROCESS_DEFINITION_ID_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须填写流程名称,并且长度不能大于{0} 的本地化字符串。
        /// </summary>
        internal static string PROCESS_DEFINITION_NAME_TOO_LONG {
            get {
                return ResourceManager.GetString("PROCESS_DEFINITION_NAME_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程定义为不可执行。 的本地化字符串。
        /// </summary>
        internal static string PROCESS_DEFINITION_NOT_EXECUTABLE {
            get {
                return ResourceManager.GetString("PROCESS_DEFINITION_NOT_EXECUTABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须填写脚本内容 的本地化字符串。
        /// </summary>
        internal static string SCRIPT_TASK_MISSING_SCRIPT {
            get {
                return ResourceManager.GetString("SCRIPT_TASK_MISSING_SCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须填写“type”或“opertaion”属性之一 的本地化字符串。
        /// </summary>
        internal static string SEND_TASK_INVALID_IMPLEMENTATION {
            get {
                return ResourceManager.GetString("SEND_TASK_INVALID_IMPLEMENTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的发送类型 的本地化字符串。
        /// </summary>
        internal static string SEND_TASK_INVALID_TYPE {
            get {
                return ResourceManager.GetString("SEND_TASK_INVALID_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须选择一种消息发送服务模板 的本地化字符串。
        /// </summary>
        internal static string SEND_TASK_TEMPLATE_NULL {
            get {
                return ResourceManager.GetString("SEND_TASK_TEMPLATE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的引用操作 的本地化字符串。
        /// </summary>
        internal static string SEND_TASK_WEBSERVICE_INVALID_OPERATION_REF {
            get {
                return ResourceManager.GetString("SEND_TASK_WEBSERVICE_INVALID_OPERATION_REF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的源 的本地化字符串。
        /// </summary>
        internal static string SEQ_FLOW_INVALID_SRC {
            get {
                return ResourceManager.GetString("SEQ_FLOW_INVALID_SRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的目标 的本地化字符串。
        /// </summary>
        internal static string SEQ_FLOW_INVALID_TARGET {
            get {
                return ResourceManager.GetString("SEQ_FLOW_INVALID_TARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的服务类型 的本地化字符串。
        /// </summary>
        internal static string SERVICE_TASK_INVALID_TYPE {
            get {
                return ResourceManager.GetString("SERVICE_TASK_INVALID_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须填写:&apos;implementation&apos;, &apos;class&apos;, &apos;delegateExpression&apos;, &apos;type&apos;, &apos;operation&apos;, or &apos;expression&apos;其中之一 的本地化字符串。
        /// </summary>
        internal static string SERVICE_TASK_MISSING_IMPLEMENTATION {
            get {
                return ResourceManager.GetString("SERVICE_TASK_MISSING_IMPLEMENTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;resultVariableName&apos; 不支持&apos;class&apos; or &apos;delegateExpression‘类型的服务 的本地化字符串。
        /// </summary>
        internal static string SERVICE_TASK_RESULT_VAR_NAME_WITH_DELEGATE {
            get {
                return ResourceManager.GetString("SERVICE_TASK_RESULT_VAR_NAME_WITH_DELEGATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的引用操作 的本地化字符串。
        /// </summary>
        internal static string SERVICE_TASK_WEBSERVICE_INVALID_OPERATION_REF {
            get {
                return ResourceManager.GetString("SERVICE_TASK_WEBSERVICE_INVALID_OPERATION_REF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的URL 的本地化字符串。
        /// </summary>
        internal static string SERVICE_TASK_WEBSERVICE_INVALID_URL {
            get {
                return ResourceManager.GetString("SERVICE_TASK_WEBSERVICE_INVALID_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效参数 的本地化字符串。
        /// </summary>
        internal static string SHELL_TASK_INVALID_PARAM {
            get {
                return ResourceManager.GetString("SHELL_TASK_INVALID_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效shell命令 的本地化字符串。
        /// </summary>
        internal static string SHELL_TASK_NO_COMMAND {
            get {
                return ResourceManager.GetString("SHELL_TASK_NO_COMMAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经存在的名称 的本地化字符串。
        /// </summary>
        internal static string SIGNAL_DUPLICATE_NAME {
            get {
                return ResourceManager.GetString("SIGNAL_DUPLICATE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找不到id为{0}的‘signalRef’ 的本地化字符串。
        /// </summary>
        internal static string SIGNAL_EVENT_INVALID_SIGNAL_REF {
            get {
                return ResourceManager.GetString("SIGNAL_EVENT_INVALID_SIGNAL_REF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须填写&apos;signalRef&apos;属性 的本地化字符串。
        /// </summary>
        internal static string SIGNAL_EVENT_MISSING_SIGNAL_REF {
            get {
                return ResourceManager.GetString("SIGNAL_EVENT_MISSING_SIGNAL_REF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的&apos;scope&apos;,仅支持&apos;global&apos; and &apos;processInstance&apos; 的本地化字符串。
        /// </summary>
        internal static string SIGNAL_INVALID_SCOPE {
            get {
                return ResourceManager.GetString("SIGNAL_INVALID_SCOPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须填写id 的本地化字符串。
        /// </summary>
        internal static string SIGNAL_MISSING_ID {
            get {
                return ResourceManager.GetString("SIGNAL_MISSING_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须填写名称 的本地化字符串。
        /// </summary>
        internal static string SIGNAL_MISSING_NAME {
            get {
                return ResourceManager.GetString("SIGNAL_MISSING_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始事件上不支持的事件定义 的本地化字符串。
        /// </summary>
        internal static string START_EVENT_INVALID_EVENT_DEFINITION {
            get {
                return ResourceManager.GetString("START_EVENT_INVALID_EVENT_DEFINITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持多启动事件 的本地化字符串。
        /// </summary>
        internal static string START_EVENT_MULTIPLE_FOUND {
            get {
                return ResourceManager.GetString("START_EVENT_MULTIPLE_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子流程不支持多启动事件 的本地化字符串。
        /// </summary>
        internal static string SUBPROCESS_MULTIPLE_START_EVENTS {
            get {
                return ResourceManager.GetString("SUBPROCESS_MULTIPLE_START_EVENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅当子流程是事件子流程时，启动事件才允许事件定义 的本地化字符串。
        /// </summary>
        internal static string SUBPROCESS_START_EVENT_EVENT_DEFINITION_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("SUBPROCESS_START_EVENT_EVENT_DEFINITION_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的中间抛出事件类型 的本地化字符串。
        /// </summary>
        internal static string THROW_EVENT_INVALID_EVENTDEFINITION {
            get {
                return ResourceManager.GetString("THROW_EVENT_INVALID_EVENTDEFINITION", resourceCulture);
            }
        }
    }
}
