using System;
using System.Collections.Generic;

/* Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace org.activiti.engine.impl.bpmn.parser.handler
{

    using org.activiti.bpmn.model;
    using org.activiti.engine.@delegate.@event;
    using org.activiti.engine.@delegate.@event.impl;
    using org.activiti.engine.impl.context;
    using org.activiti.engine.impl.persistence.entity;

    /// 
    public class ProcessParseHandler : AbstractBpmnParseHandler<Process>
    {
        public const string PROPERTYNAME_DOCUMENTATION = "documentation";

        protected internal override Type HandledType
        {
            get
            {
                return typeof(Process);
            }
        }

        protected internal override void executeParse(BpmnParse bpmnParse, Process process)
        {
            if (process.Executable == false)
            {
                //LOGGER.info("Ignoring non-executable process with id='" + process.Id + "'. Set the attribute isExecutable=\"true\" to deploy this process.");
            }
            else
            {
                bpmnParse.ProcessDefinitions.Add(transformProcess(bpmnParse, process));
            }
        }

        protected internal virtual IProcessDefinitionEntity transformProcess(BpmnParse bpmnParse, Process process)
        {
            IProcessDefinitionEntity currentProcessDefinition = Context.CommandContext.ProcessDefinitionEntityManager.create();
            bpmnParse.CurrentProcessDefinition = currentProcessDefinition;

            /*
             * Mapping object model - bpmn xml: processDefinition.id -> generated by activiti engine processDefinition.key -> bpmn id (required) processDefinition.name -> bpmn name (optional)
             */
            currentProcessDefinition.Key = process.Id;
            currentProcessDefinition.Name = process.Name;
            currentProcessDefinition.Category = bpmnParse.BpmnModel.TargetNamespace;
            currentProcessDefinition.Description = process.Documentation;
            currentProcessDefinition.DeploymentId = bpmnParse.Deployment.Id;

            if (!string.ReferenceEquals(bpmnParse.Deployment.EngineVersion, null))
            {
                currentProcessDefinition.EngineVersion = bpmnParse.Deployment.EngineVersion;
            }

            createEventListeners(bpmnParse, process.EventListeners);

            //if (LOGGER.DebugEnabled)
            //{
            //    LOGGER.debug("Parsing process {}", currentProcessDefinition.Key);
            //}

            bpmnParse.processFlowElements(process.FlowElements);
            processArtifacts(bpmnParse, process.Artifacts);

            return currentProcessDefinition;
        }

        protected internal virtual void createEventListeners(BpmnParse bpmnParse, IList<EventListener> eventListeners)
        {

            if (eventListeners != null && eventListeners.Count > 0)
            {
                foreach (EventListener eventListener in eventListeners)
                {
                    // Extract specific event-types (if any)
                    ActivitiEventType[] types = ActivitiEventType.getTypesFromString(eventListener.Events);

                    if (ImplementationType.IMPLEMENTATION_TYPE_CLASS.Equals(eventListener.ImplementationType))
                    {
                        getEventSupport(bpmnParse.BpmnModel).addEventListener(bpmnParse.ListenerFactory.createClassDelegateEventListener(eventListener), types);

                    }
                    else if (ImplementationType.IMPLEMENTATION_TYPE_DELEGATEEXPRESSION.Equals(eventListener.ImplementationType))
                    {
                        getEventSupport(bpmnParse.BpmnModel).addEventListener(bpmnParse.ListenerFactory.createDelegateExpressionEventListener(eventListener), types);

                    }
                    else if (ImplementationType.IMPLEMENTATION_TYPE_THROW_SIGNAL_EVENT.Equals(eventListener.ImplementationType) || ImplementationType.IMPLEMENTATION_TYPE_THROW_GLOBAL_SIGNAL_EVENT.Equals(eventListener.ImplementationType) || ImplementationType.IMPLEMENTATION_TYPE_THROW_MESSAGE_EVENT.Equals(eventListener.ImplementationType) || ImplementationType.IMPLEMENTATION_TYPE_THROW_ERROR_EVENT.Equals(eventListener.ImplementationType))
                    {

                        getEventSupport(bpmnParse.BpmnModel).addEventListener(bpmnParse.ListenerFactory.createEventThrowingEventListener(eventListener), types);

                    }
                    else
                    {
                        //LOGGER.warn("Unsupported implementation type for EventListener: " + eventListener.ImplementationType + " for element " + bpmnParse.CurrentFlowElement.Id);
                    }
                }
            }

        }

        protected internal virtual ActivitiEventSupport getEventSupport(BpmnModel bpmnModel)
        {
            return (ActivitiEventSupport)bpmnModel.EventSupport;
        }

    }

}