/*导出部署数据*/
SELECT ID_,NAME_,BUSINESS_KEY_,CATEGORY_,KEY_,TENANT_ID_,DEPLOY_TIME_,ENGINE_VERSION_ 
FROM activiti.ACT_RE_DEPLOYMENT 
order by DEPLOY_TIME_ desc limit 2;

/*导出流程定义数据*/
SELECT a.ID_, a.REV_, a.CATEGORY_, a.NAME_, a.BUSINESS_KEY_, a.BUSINESS_PATH_, a.START_FORM_, a.KEY_,
a.VERSION_, a.DEPLOYMENT_ID_, a.RESOURCE_NAME_, a.DGRM_RESOURCE_NAME_, a.DESCRIPTION_, a.HAS_START_FORM_KEY_, 
a.HAS_GRAPHICAL_NOTATION_, a.SUSPENSION_STATE_, a.TENANT_ID_, a.ENGINE_VERSION_
FROM activiti.ACT_RE_PROCDEF a
inner join activiti.ACT_RE_DEPLOYMENT b  on a.DEPLOYMENT_ID_ = b.ID_
order by b.DEPLOY_TIME_ desc
limit 2;

/*导出xml数据*/
SELECT a.ID_, a.REV_, a.NAME_, a.DEPLOYMENT_ID_, a.BYTES_, a.GENERATED_ 
FROM activiti.ACT_GE_BYTEARRAY a
inner join activiti.ACT_RE_DEPLOYMENT b  on a.DEPLOYMENT_ID_ = b.ID_
order by b.DEPLOY_TIME_ desc
limit 2;